services:
  highlights-fetch-service:
    build: ./highlights-fetch-service
    ports:
      - "8000:8000"
    env_file:
      - ./highlights-fetch-service/.env
    volumes:
      - ./highlights-fetch-service:/app

  library-ui:
    build: ./library-ui
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - highlights-fetch-service
    volumes:
      - ./library-ui:/app
      - /app/node_modules
    command: npm run dev

