[providers]
python = "3.13"

[phases.setup]
nixPkgs = ['python313', 'bash']

[phases.install]
cmds = ['pip install --upgrade pip', 'pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'bash start.sh'
