[phases.setup]
nixPkgs = ['python313', 'pip']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'uvicorn main:app --host 0.0.0.0 --port $PORT --workers 4'
